version: "3.7"

volumes:
# Druid
    metadata_data: {}
    druid_middle_var: {}
    historical_var: {}
    druid_broker_var: {}
    druid_coordinator_var: {}
    druid_router_var: {}

services:
    # Need 3.6 or later for container nodes
    zookeeper:
        # container_name: zookeeper
        image: zookeeper:3.6
        environment:
            - ZOO_MY_ID=1

# Druid
    druid_postgres:
        container_name: druid_postgres
        image: postgres:latest
        volumes:
            - metadata_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=FoolishPassword
            - POSTGRES_USER=druid
            - POSTGRES_DB=druid

    druid_coordinator:
        image: apache/druid:0.17.0
        container_name: druid_coordinator
        volumes:
            - ./storage:/opt/data
            - druid_coordinator_var:/opt/druid/var
        depends_on: 
            - zookeeper
            - druid_postgres
        ports:
            - "8081:8081"
        command:
            - coordinator
        env_file:
            - druid.env

    druid_broker:
        image: apache/druid:0.17.0
        container_name: druid_broker
        volumes:
             - druid_broker_var:/opt/druid/var
        depends_on: 
            - zookeeper
            - druid_postgres
            - druid_coordinator
        ports:
            - "8082:8082"
        command:
            - broker
        env_file:
            - druid.env

    druid_historical:
        image: apache/druid:0.17.0
        container_name: druid_historical
        volumes:
            - ./storage:/opt/data
            - historical_var:/opt/druid/var
        depends_on: 
            - zookeeper
            - druid_postgres
            - druid_coordinator
        ports:
            - "8083:8083"
        command:
            - historical
        env_file:
            - druid.env

    druid_middlemanager:
        image: apache/druid:0.17.0
        container_name: druid_middlemanager
        volumes:
            - ./storage:/opt/data
            - druid_middle_var:/opt/druid/var
        depends_on: 
            - zookeeper
            - druid_postgres
            - druid_coordinator
        ports:
            - "8091:8091"
        command:
            - middleManager
        env_file:
            - druid.env

    druid_router:
        image: apache/druid:0.17.0
        container_name: druid_router
        volumes:
            - druid_router_var:/opt/druid/var
        depends_on:
            - zookeeper
            - druid_postgres
            - druid_coordinator
        ports:
            - "8888:8888"
        command:
            - router
        env_file:
            - druid.env